# Generated by Django 4.2.6 on 2023-12-24 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_answer_likes_remove_question_likes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='likes',
            field=models.ManyToManyField(related_name='liked_questions', to='app.profile'),
        ),
    ]
